[workspace]
members = [".", "corefs-core"]
resolver = "2"

[workspace.package]
version = "0.1.19"
edition = "2024"
license = "MIT"
authors = ["Mike Strathmann"]

[workspace.dependencies]
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
bincode = { version = "1" }

[package]
name = "corefs"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
corefs-core = { path = "corefs-core", features = ["std"] }
bincode = { workspace = true }
chacha20poly1305 = { version = "0.10", default-features = false, features = ["alloc", "getrandom"] }
lz4_flex = { version = "0.11", default-features = false, features = ["frame"] }
serde = { workspace = true, features = ["std"] }
serde_json = "1"

[target.'cfg(target_os = "linux")'.dependencies]
fuser = "0.14"
libc = "0.2"
